services:
  payload:
    image: registry.cevi.tools/cevi/conveniat27-webpage:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_VAPID_PUBLIC_KEY=BGXpnSSQfJS84zCk6qka6-3qC_bTK6feOUaLz6ZJY6ThmdcY-h20V0QB8P8nq84Pb6vpbZLvYwISwlSmH9aZwjU
        - NEXT_PUBLIC_APP_HOST_URL=https://conveniat27.ch
        - NEXT_PUBLIC_POSTHOG_KEY=phc_QXeG5AHoyxCVCcIse8a2rriQKZgAwkk3vO15Zz0aDud
        - NEXT_PUBLIC_POSTHOG_HOST=https://eu.i.posthog.com

    deploy:
      labels:
        - swarmpit.service.deployment.autoredeploy=true

        - traefik.enable=true

        # redirect conveniat.ch (HTTPS)
        - traefik.http.routers.conveniat-redirect-secure.rule=Host(`conveniat.ch`)
        - traefik.http.routers.conveniat-redirect-secure.entrypoints=websecure
        - traefik.http.routers.conveniat-redirect-secure.middlewares=redirect-to-conveniat27-from-conveniat

        - traefik.http.middlewares.redirect-to-conveniat27-from-conveniat.redirectregex.regex=^https?://conveniat.ch/(.*)
        - traefik.http.middlewares.redirect-to-conveniat27-from-conveniat.redirectregex.replacement=https://conveniat27.ch/$$$${1}
        - traefik.http.middlewares.redirect-to-conveniat27-from-conveniat.redirectregex.permanent=true

        # redirect conveniat.ch (HTTP to HTTPS for redirect)
        - traefik.http.routers.conveniat-redirect-http.rule=Host(`conveniat.ch`)
        - traefik.http.routers.conveniat-redirect-http.entrypoints=web
        - traefik.http.routers.conveniat-redirect-http.middlewares=redirect-to-https@file

        # short url
        - traefik.http.routers.short-con27-router.rule=Host(`con27.ch`)
        - traefik.http.routers.short-con27-router.entrypoints=websecure
        - traefik.http.routers.short-con27-router.middlewares=redirect-to-conveniat27
        - traefik.http.middlewares.redirect-to-conveniat27.redirectregex.regex=^https?://con27.ch/(.*)
        - traefik.http.middlewares.redirect-to-conveniat27.redirectregex.replacement=https://conveniat27.ch/go/$$$${1}
        - traefik.http.middlewares.redirect-to-conveniat27.redirectregex.permanent=true

        - traefik.http.routers.con27-router-http.rule=Host(`con27.ch`)
        - traefik.http.routers.con27-router-http.entrypoints=web
        - traefik.http.routers.con27-router-http.middlewares=redirect-to-https@file

        # HTTP gets redirected to HTTPS
        - traefik.http.routers.conveniat27-router-http.rule=Host(`conveniat27.ch`) || Host(`www.conveniat27.ch`)
        - traefik.http.routers.conveniat27-router-http.entrypoints=web
        - traefik.http.routers.conveniat27-router-http.middlewares=redirect-to-https@file

        - traefik.http.routers.conveniat27-router.rule=Host(`conveniat27.ch`) || Host(`www.conveniat27.ch`)
        - traefik.http.routers.conveniat27-router.entrypoints=websecure
        - traefik.http.routers.conveniat27-router.service=conveniat27
        - traefik.http.routers.conveniat27-router.middlewares=conveniat27-to-non-www

        - traefik.http.services.conveniat27.loadbalancer.server.port=3000

        - traefik.http.middlewares.conveniat27-to-non-www.redirectregex.regex=^https://www.conveniat27.ch/(.*)
        - traefik.http.middlewares.conveniat27-to-non-www.redirectregex.replacement=https://conveniat27.ch/$$$${1}
        - traefik.http.middlewares.conveniat27-to-non-www.redirectregex.permanent=true

      resources:
        reservations:
          cpus: '0.5'
          memory: 256M
        limits:
          cpus: '1.0'
          memory: 512M

    volumes:
      - /cluster/swarm/data/conveniat/next-cache:/app/.next/cache

    dns:
      - 8.8.8.8 # Replace with your desired DNS server

    depends_on:
      - mongo
    env_file:
      - .env

    networks:
      - traefik-net
      - backend-net

  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - /cluster/swarm/data/conveniat-prod/mongodb-data:/data/db
    logging:
      driver: none

    networks:
      - backend-net

  minio:
    image: minio/minio

    deploy:
      labels:
        - swarmpit.service.deployment.autoredeploy=true
        - traefik.enable=true

        - traefik.http.routers.conveniat-minio-router-http.rule=Host(`minio.conveniat27.ch`)
        - traefik.http.routers.conveniat-minio-router-http.entrypoints=web
        - traefik.http.routers.conveniat-minio-router-http.middlewares=redirect-to-https@file

        - traefik.http.routers.conveniat-minio-router-console-http.rule=Host(`console-minio.conveniat27.ch`)
        - traefik.http.routers.conveniat-minio-router-console-http.entrypoints=web
        - traefik.http.routers.conveniat-minio-router-console-http.middlewares=redirect-to-https@file

        - traefik.http.routers.conveniat-minio-router.rule=Host(`minio.conveniat27.ch`)
        - traefik.http.routers.conveniat-minio-router.entrypoints=websecure
        - traefik.http.routers.conveniat-minio-router.service=conveniat-minio

        - traefik.http.routers.conveniat-console-minio-router.rule=Host(`console-minio.conveniat27.ch`)
        - traefik.http.routers.conveniat-console-minio-router.entrypoints=websecure
        - traefik.http.routers.conveniat-console-minio-router.service=conveniat-console-minio

        - traefik.http.services.conveniat-minio.loadbalancer.server.port=9000
        - traefik.http.services.conveniat-console-minio.loadbalancer.server.port=9001

    command: server --console-address ":9001" /data

    env_file:
      - .env

    volumes:
      - /cluster/swarm/data/conveniat-prod/minio-data:/data

    networks:
      - traefik-net
      - backend-net

  postgres:
    image: postgres:17

    deploy:
      labels:
        - swarmpit.service.deployment.autoredeploy=true

        # expose the DB via tcp on port 443
        - traefik.enable=true
        - traefik.tcp.routers.conveniat27-database.entrypoints=websecure
        - traefik.tcp.routers.conveniat27-database.rule=HostSNI(`db.conveniat27.ch`)

        # define TLS
        - traefik.tcp.routers.conveniat27-database.tls=true
        - traefik.tcp.routers.conveniat27-database.tls.certresolver=myresolver
        - traefik.tcp.routers.conveniat27-database.middlewares=vpn-whitelist@file

        - traefik.tcp.services.conveniat27-database.loadbalancer.server.port=5432

    env_file:
      - .env

    volumes:
      - /cluster/swarm/data/conveniat-prod/postgres:/var/lib/postgresql/data

    networks:
      - backend-net
      - traefik-net

networks:
  traefik-net:
    external: true

  backend-net:
    driver: overlay
    attachable: true
