services:
  payload:
    image: node:22-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - next-cache:/home/node/app/.next
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && sh /home/node/app/create_build_info.sh &&  pnpm install && pnpm dev"
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command: mongod --quiet --logpath /dev/null  --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

  mongo-express:
    image: mongo-express
    ports:
      - '8081:8081'
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: 'admin'
      ME_CONFIG_BASICAUTH_PASSWORD: 'pass'
      ME_CONFIG_MONGODB_SERVER: mongo
    logging:
      driver: none

  minio:
    image: minio/minio

    entrypoint: sh
    command: >
      -c "mkdir -p /data/${MINIO_BUCKET_NAME} &&
      /usr/bin/minio server --console-address ':9001' /data & 
      sleep 10 &&
      mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      mc admin user svcacct add --access-key '${MINIO_ACCESS_KEY_ID}' --secret-key '${MINIO_SECRET_ACCESS_KEY}' myminio ${MINIO_ROOT_USER} || true &&
      echo 'minio is ready' &&
      sleep infinity"

    env_file:
      - .env

    ports:
      - 9000:9000
      - 9001:9001

    volumes:
      - miniodata:/data

volumes:
  data:
  node_modules:
  next-cache:
  miniodata:
