services:
  payload:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - next-cache:/home/node/app/.next
      - node-cache:/nodecache
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: >
      sh -c "corepack enable pnpm && pnpm i --frozen-lockfile &&
      sh /home/node/app/create_build_info.sh &&
      if [ \"$ENABLE_SERVICE_WORKER_LOCALLY\" = \"true\" ]; then
        echo '' &&
        echo '**************************************************' &&
        echo '*   WARNING: SERVICE WORKER ENABLED              *' &&
        echo '*   Turbopack is DISABLED. Dev server will be    *' &&
        echo '*   significantly SLOWER.                        *' &&
        echo '**************************************************' &&
        echo '' &&
        pnpm devsafe
      else
        echo 'Service worker disabled' &&
        pnpm dev
      fi"
    dns:
      - 8.8.8.8
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - NODE_COMPILE_CACHE=/nodecache  # see https://nodejs.org/en/blog/release/v22.1.0

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command: mongod --quiet --logpath /dev/null  --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

  mongo-express:
    image: mongo-express
    ports:
      - '8081:8081'
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: 'admin'
      ME_CONFIG_BASICAUTH_PASSWORD: 'pass'
      ME_CONFIG_MONGODB_SERVER: mongo
    logging:
      driver: none

  minio:
    image: minio/minio

    entrypoint: sh
    command: >
      -c "mkdir -p /data/${MINIO_BUCKET_NAME} &&
      /usr/bin/minio server --console-address ':9001' /data & 
      sleep 10 &&
      mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      mc admin user svcacct add --access-key '${MINIO_ACCESS_KEY_ID}' --secret-key '${MINIO_SECRET_ACCESS_KEY}' myminio ${MINIO_ROOT_USER} || true &&
      echo 'minio is ready' &&
      sleep infinity"

    env_file:
      - .env

    ports:
      - '9000:9000'
      - '9001:9001'

    volumes:
      - minio-data:/data

  fake-oauth:
    build: dev-oauth
    ports:
      - '3001:5000'
    restart: always

volumes:
  data:
  node_modules:
  next-cache:
  minio-data:
  node-cache:
