services:
  payload:
    image: registry.cevi.tools/cevi/conveniat27-webpage:latest
    build:
      context: .
      dockerfile: Dockerfile

    deploy:
      labels:
        - swarmpit.service.deployment.autoredeploy=true

        # Enable Traefik for this service, to make it available in the public network
        - traefik.enable=true

        # HTTP gets redirected to HTTPS
        - traefik.http.routers.conveniat27-router-http.rule=Host(`test.conveniat27.cevi.tools`)
        - traefik.http.routers.conveniat27-router-http.entrypoints=web
        - traefik.http.routers.conveniat27-router-http.middlewares=redirect-to-https@file

        - traefik.http.routers.conveniat27-router.rule=Host(`test.conveniat27.cevi.tools`)
        - traefik.http.routers.conveniat27-router.entrypoints=websecure
        - traefik.http.routers.conveniat27-router.service=conveniat27

        - traefik.http.services.conveniat27.loadbalancer.server.port=3000

    ports:
      - '3000:3000'
    depends_on:
      - mongo
    env_file:
      - .env

    networks:
      - traefik-net
      - backend-net

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

    networks:
      - backend-net

volumes:
  data:

networks:
  traefik-net:
    external: true

  backend-net:
    driver: overlay
    attachable: true
