on:
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: Use Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '22'

      - name: Install prettier
        run: yarn add prettier

      - name: Run prettier
        run: yarn prettier:check

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: yarn lint